<nav id="navigation-main">
  <ul>
    <li><a href="#"><i class="typcn typcn-home-outline"></i> Home</a></li>
    <li><a href="#"><i class="typcn typcn-message"></i> Blog</a></li>
    <li><a href="#"><i class="typcn typcn-document-text"></i> Articles</a></li>
    <li><a href="#"><i class="typcn typcn-folder"></i> Projects</a></li>
    <li><a href="#"><i class="typcn typcn-info-large-outline"></i> About</a></li>
  </ul>
</nav>