<header id="page-header">
  <div id="page-header-logo">
    <img src="images/logo.svg" alt="Logo of the J-site." >
  </div>
  <div>
    <span id="page-header-sitename">Jelle van Campen</span>
    <span id="page-header-pagename">Responsive layouts using CSS Flex</span>
    <span id="page-header-breadcrumb">Article <i class="typcn typcn-media-play"></i> Tutorial <i class="typcn typcn-media-play"></i> Responsive layouts using CSS Flex</span>   
  </div>
</header>