<meta charset="utf-8">
<meta name="title" content="Computer Science, Graphics, and Games | The J-site">
<meta name="description" content="Hi! The J-site is my channel for highlighting the magic in everyday computer technology. I keep a blog, write articles and create projects. See you inside!">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="apple-mobile-web-app-title" content="J-site">
<meta name="application-name" content="J-site">
<meta name="theme-color" content="#ffffff">

<link href="https://fonts.googleapis.com/css?family=Lora:400,700i|Roboto:300,300i|Space+Mono" rel="stylesheet">
<link ref="stylesheet" href="normalize.css">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="fonts/typicons/typicons.min.css" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">

<title>Home | J-site</title>

<script src="scripts/jquery-3.2.0.min.js" defer></script>
<script src="scripts/general.js" defer></script>